baseURL: "https://orsha.linux.by/"
languageCode: "ru"
theme: "beautifulhugo"
DefaultContentLanguage: "ru"
title: "Orsha LUG"
description: "Группа пользователей Linux в Орше"
metaDataFormat: "yaml"
# disableRSS: true
disableKinds:
    - RSS
    - taxonomy
    - taxonomyTerm

pygmentsStyle: "trac"
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true

googleAnalytics: UA-100726130-1

Params:
    subtitle: 'Группа пользователей Linux в Орше'
    logo: "images/orsha-tux-hugo.png"
    favicon: "favicon.ico"
    commit: false
    rss: false
    readingTime: false
    # @todo: https://gohugo.io/content-management/multilingual/
    # @todo: do pull requests to the theme
    dateFormat: "2006-01-02"

menu:
  main:
      - Name: "Форум"
        Weight: -1
        URL: "/forum/"
      - Name: "Статьи"
        Weight: 2
        URL: "/article/"
      - Name: "Манифест"
        Weight: 2
        URL: "/article/manifest/"


Author:
    name: "OrshaLUG"
    website: "https://orsha.linux.by/"
    email: "orsha-lug@googlegroups.com"
    telegram: "joinchat/EfXjtg4f0DrD-N6u8k2hig"

