baseURL: "http://orsha.linux.by/"
languageCode: "ru"
theme: "beautifulhugo"
DefaultContentLanguage: "ru"
title: "Orsha LUG"
description: "Группа пользователей Linux в Орше"
metaDataFormat: "yaml"

pygmentsStyle: "trac"
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true

Params:
    subtitle: 'Группа пользователей Linux в Орше'
    logo: "images/orsha-tux-hugo.png"
    favicon: "images/tux_orsha.png"
    commit: false
    rss: false
    readingTime: false
    # @todo: https://gohugo.io/content-management/multilingual/
    # @todo: do pull requests to the theme
    dateFormat: "2006-01-02"

menu:
  main:
      - Name: "Форум"
        Weight: -1
        URL: "/forum/"
      - Name: "Статьи"
        Weight: 2
        URL: "/getting-started/"
      - Name: "Манифест"
        Weight: 2
        URL: "/getting-started/"


# Author:
#     name: "OrshaLUG"
#     website: "https://orsha.linux.by/"
#     email: "orsha-lug@googlegroups.com"
#     telegram: "Orsha LUG"

